name: firebase-hosting-deploy-o-to

#マスターブランチにプッシュされたら実行される
on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest # ubuntuの最新バージョンで実行する
    steps: # 実行されるコマンドたち
      - uses: actions/checkout@master
      - uses: w9jds/firebase-action@master
        with: # 引数
          args: deploy --only hosting #変更をデプロイする
        env: # 環境変数
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # GitHub側に登録した環境変数を引っ張ってくる
